name: random_bot
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  teledart: ^0.0.39
  dio: ^3.0.9
  equatable: ^1.1.1
  intl: ^0.16.1
  dotenv: ^2.0.0
  
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  appengine: ^0.10.5
  logging: ^0.11.4

